COUNTRY_NAME_DICT = {
    "ch": "Switzerland",
    "eu": "European",
    "all": "Europe Union",
    #       "al": "Albania",
    #       "am": "Armenia",
    "at": "Austria",
    #       "az": "Azerbaijan",
    "ba": "Bosnia-Herzegovina",
    "be": "Belgium",
    #       "by": "Belarus",
    "cy": "Cyprus",
    "cz": "Czech Republic",
    "de": "Germany",
    "dk": "Denmark",
    "ee": "Estonia",
    "es": "Spain",
    "fi": "Finland",
    "fr": "France",
    "ge": "Georgia",
    "gr": "Greece",
    "hr": "Croatia",
    "hu": "Hungary",
    "ie": "Ireland",
    "it": "Italy",
    "lt": "Lithuania",
    "lu": "Luxembourg",
    "lv": "Latvia",
    "md": "Moldova",
    "me": "Montenegro",
    "mk": "North Macedonia",
    #       "mt": "Malta",
    #       "nie": "North Ireland",
    "nl": "Netherlands",
    "no": "Norway",
    "pl": "Poland",
    "pt": "Portugal",
    "ro": "Romania",
    "rs": "Serbia",
    #       "ru": "Russia",
    "se": "Sweden",
    #       "sl": "Slovenia",
    "sk": "Slovak Republic",
    #       "tr": "Turkey",
    "ua": "Ukraine",
    "uk": "United Kingdom",
    "xk": "Kosovo",
}

POWER_COLUMN_NAME_DICT = {
    "Battery Storage (Power)": "battery_storage_power",
    "Battery Storage (Capacity)": "battery_storage_capacity",
    "Hydro pumped storage consumption": "hydro_pumped_storage_cons",
    "Cross border electricity trading": "cross_border_trading",
    "Import Balance": "import_balance",
    "Nuclear": "nuclear",
    "Hydro Run-of-River": "hydro_run_of_river",
    "Biomass": "biomass",
    "Fossil brown coal / lignite": "fossil_brown_coal",
    "Fossil hard coal": "fossil_hard_coal",
    "Fossil oil": "fossil_oil",
    "Fossil coal-derived gas": "fossil_coal_gas",
    "Fossil peat": "fossil_peat",
    "Fossil gas": "fossil_gas",
    "Geothermal": "geothermal",
    "System inertia": "system_inertia",
    "Hydro water reservoir": "hydro_water_reservoir",
    "Hydro pumped storage": "hydro_pumped_storage",
    "Others": "others",
    "Waste": "waste",
    "Wind offshore": "wind_offshore",
    "Wind onshore": "wind_onshore",
    "Solar": "solar",
    "Other renewables": "other_renewables",
    "Other, non-renewable": "other_non_renewable",
    "Marine": "marine",
    "Load": "load",
    "Load (incl. self-consumption)": "load_incl_self_consumption",
    "Fossil oil shale": "fossil_oil_shale",
    "Residual load": "residual_load",
    "Renewable share of generation": "renewable_gen_share",
    "Renewable share of load": "renewable_load_share",
}
